### ISSUE TITLE
feat: 与后端进行接口层面上的对接与联调

### ISSUE THREAD

**Issue by nonhana** [nonhana/Picals-Frontend-React#35]
- [x] 对 axios 进行类式二次封装，提供错误捕获机制、无感刷新 token 机制 #36 
- [x] 将接口以函数形式封装在 apis 目录下 #37 
- [x] 前后端进行接口联调（这里可能得拆成很多个 issue） #57

**Comment by nonhana** [comment]
至此，V0beta完成
